version: 0.2

phases:
  pre_build:
    commands:
      - ls
      - aws --version
      - sam --version
      - go version
      - go mod init handler
      - go mod tidy
      - sam build
      - sam deploy --stack-name $STACK_NAME --s3-bucket $BUCKET_NAME --no-confirm-changeset --capabilities CAPABILITY_IAM
  build:
    commands:
      - sam build
      - ls
